image: golang:latest

stages:
  - test

test:
  stage: test
  script:
    - go mod download
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

coverage:
  stage: test
  script:
    - go install
    - go test $(go list ./... | grep -v vendor) -race -coverprofile=coverage.out
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.out > coverage.xml
    - go tool cover -func=coverage.out
  artifacts:
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /total:\s+\(statements\)\s+(\d+.\d+\%)/
